"""
Django settings for turbodiaz project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import json
from django.utils.html import  format_html



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

##conf.json datos de configuracion##
ruta= os.path.dirname(os.path.abspath(__file__))
f = open('{}/conf.json'.format(ruta), 'r')
conf_string = f.read()
f.close()
conf = json.loads(conf_string)
####################################

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$dfn-goxh+oso6&gy+xwj(rrz9%o@r&+ybw190&zvo59ma$&kk'

#email despues cambiar el correo de turbodiaz


#*****
BASE_URL=conf['base_url']
TOTAL_PAGINAS=conf['paginacion']
RUTA=conf['ruta']
RUTA2=conf['ruta2']

#envío mail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'turbodiaz.cl@gmail.com'
EMAIL_HOST_PASSWORD = 'pagh jhzh izto dwhl'
EMAIL_HOST_USER = 'turbodiaz.cl@gmail.com'


WEBPAY_URL=conf['webpay_url']
WEBPAY_ID=conf['webpay_id']
WEBPAY_SECRET=conf['webpay_secret']
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = conf['debug']

ALLOWED_HOSTS = ['127.0.0.1']

#RECAPTCHA
#TU_CLAVE_DEL_SITIO
RECAPTCHA_PUBLIC_KEY = '6LdMlI8qAAAAANnWWeEtxXNqF3YirDfOKpeCNoPM'
#TU_CLAVE_SECRETA
RECAPTCHA_PRIVATE_KEY = '6LdMlI8qAAAAAAavKWutThuJRIKUYWQXbbP1YWo-'

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    #admin interface--------
    'admin_interface',
    'colorfield',
   
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #mis app
    
    'home'
]

#ADMIN JAZZMIN
JAZZMIN_SETTINGS = {
    "site_title": "Administración Tienda",
    "site_header": "Administración Tienda",
    "site_brand": "Turbodiaz",
    "welcome_sign": "Bienvenido a la administración de Turbodiaz",
    "show_sidebar": True,
    "navigation_expanded": True,
    "topmenu_links": [
        {"name": "Inicio", "url": "/", "permissions": ["auth.view_user"]},
        {"name": "Soporte", "url": "https://soporte.turbodiaz.cl", "new_window": True},
    ],
    "user_avatar": None,
    "hide_apps": ["auth"],
    "hide_models": ["auth.Group"],
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'turbodiaz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'turbodiaz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': conf['bd'],
        'USER': conf['user'],
        'PASSWORD': conf['password'],
        'HOST': conf['server'],
        'PORT': conf['puerto'],
        'OPTIONS':{
          'autocommit': True,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/assets/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'),
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#RECAPTCHA
#TU_CLAVE_DEL_SITIO
RECAPTCHA_PUBLIC_KEY = '6LdMlI8qAAAAANnWWeEtxXNqF3YirDfOKpeCNoPM'
#TU_CLAVE_SECRETA
RECAPTCHA_PRIVATE_KEY = '6LdMlI8qAAAAAAavKWutThuJRIKUYWQXbbP1YWo-'
