# Generated by Django 3.2 on 2024-09-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado')], default='Activo', max_length=10)),
                ('numero_pedido', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, choices=[('negro', 'Negro'), ('blanco', 'Blanco')], max_length=10, null=True)),
                ('talla', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, null=True)),
                ('ancho', models.CharField(blank=True, choices=[('45 cm', '45 cm'), ('50 cm', '50 cm'), ('55 cm', '55 cm'), ('60 cm', '60 cm'), ('66 cm', '66 cm'), ('71 cm', '71 cm')], max_length=5, null=True)),
                ('alto', models.CharField(blank=True, choices=[('70 cm', '70 cm'), ('73 cm', '73 cm'), ('75 cm', '75 cm'), ('78 cm', '78 cm'), ('80 cm', '80 cm'), ('85 cm', '85 cm')], max_length=5, null=True)),
                ('tamaño', models.CharField(blank=True, choices=[('chico', 'Chico'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=10, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('imagen_trasera', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('nombre_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('pago', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
