# Generated by Django 3.2 on 2024-09-17 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='Keyword',
            new_name='keyword',
        ),
    ]
