# Generated by Django 3.2 on 2024-10-18 02:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_rename_keyword_metadata_keyword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductosFotos',
            new_name='ProductoFotos',
        ),
        migrations.RenameModel(
            old_name='UsersMetada',
            new_name='UsersMetadata',
        ),
    ]
