# Generated by Django 4.2.16 on 2024-11-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20241017_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordendecompra',
            options={'verbose_name': 'Orden de compra', 'verbose_name_plural': 'Órdenes de compra'},
        ),
    ]
