# Generated by Django 4.2.16 on 2024-12-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_ordendecompra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='envio',
            field=models.CharField(choices=[('starken', 'Starken'), ('chilexpress', 'Chilexpress'), ('correoschile', 'CorreosChile')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='rut',
            field=models.CharField(default='', help_text='RUT en formato 12.345.678-9', max_length=12),
        ),
    ]
