# Generated by Django 4.2.16 on 2024-12-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_ordendecompra_envio_remove_ordendecompra_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='envio_a_regiones',
            field=models.CharField(blank=True, choices=[('Starken', 'Starken'), ('Chilexpress', 'Chilexpress'), ('CorreosChile', 'CorreosChile')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
