# Generated by Django 4.2.16 on 2024-12-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ordendecompra_envio_a_regiones_ordendecompra_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendecompra',
            name='envio_a_regiones',
        ),
        migrations.RemoveField(
            model_name='ordendecompra',
            name='rut',
        ),
    ]
