# Generated by Django 4.2.16 on 2024-12-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_ordendecompra_envio_a_regiones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='envio_a_regiones',
            field=models.CharField(choices=[('Starken', 'Starken'), ('Chilexpress', 'Chilexpress'), ('CorreosChile', 'CorreosChile')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ordendecompra',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
