# Generated by Django 4.2.16 on 2024-12-03 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ordendecompra_envio_a_regiones_ordendecompra_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
