# Generated by Django 4.2.16 on 2024-12-06 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_ordendecompra_fecha_emision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('users_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usersmetadata')),
            ],
        ),
    ]
