# Generated by Django 4.2.16 on 2024-12-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_activitylog_users_metadata_activitylog_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
