# Generated by Django 4.2.16 on 2024-12-06 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user_metadata',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='users_metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usersmetadata'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
