# Generated by Django 4.2.16 on 2024-12-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
