# Generated by Django 4.2.16 on 2024-12-07 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
